---
title: "Deutscher Wetterdienst (DWD)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Deutscher Wetterdienst (DWD)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Define Helper Functions

```{r define_helpers}
group_by_decade_month_label <- function(data) {
  data %>%
    dplyr::group_by(
      .data$Dekade,
      .data$Dekade_Label, 
      .data$Monat, 
      .data$Label
    )
}

group_by_decade_label <- function(data) {
  data %>%
    dplyr::group_by(.data$Dekade_Label)
}

group_by_year_month <- function(data) {
  data %>%
    dplyr::group_by(.data$Jahr, .data$Monat)
}

summarise_means <- function(data) {
  data %>%
    dplyr::summarise(
      q05 = quantile(.data$mean, probs = 0.05),
      q95 = quantile(.data$mean, probs = 0.95),
      mean = mean(.data$mean)
    )  
}
```

```{r setup}
library(kwb.impetus)

DT::datatable(kwb.impetus::dwd_berlin_monthly)
```

## Create Plots

```{r no_messages, echo = FALSE}
options(dplyr.summarise.inform = FALSE)
```

### Precipitation

```{r precipitation}
para_name <- "precipitation"

precipitation <- kwb.impetus::dwd_berlin_monthly %>% 
  dplyr::filter(.data$parameter == para_name) %>%  
  dplyr::mutate(
    Jahr = as.integer(.data$year), 
    Dekade = kwb.impetus::floor_decade(.data$year),
    Dekade_Label = kwb.impetus::decade_label(.data$Dekade),
    Monat = as.factor(.data$month),
    Label = sprintf("DWD, monthly %s", .data$parameter)
  )

precipitation_agg <- precipitation %>% 
  group_by_decade_month_label() %>% 
  summarise_means()

n_decades <- length(unique(precipitation_agg$Dekade_Label))

decade_colors <- c('darkblue', 'blue', 'darkgreen', 'lightgreen', 'orange', 'red')

n_colors <- length(decade_colors)

n_colors_to_fill <- n_decades - n_colors

decades <- tibble::tibble(
  names = unique(precipitation_agg$Dekade_Label)[order(unique(precipitation_agg$Dekade_Label))],
  values = c(
    rep("black", n_colors_to_fill), 
    'darkblue',
    'blue', 
    'darkgreen', 
    'lightgreen', 
    'orange', 
    'red'
  )
)

precipitation_decade_annual <- precipitation_agg %>%  
  group_by_decade_label() %>% 
  dplyr::summarise(annual_mean = sum(.data$mean))

kwb.utils::preparePdf(
  "dwd_monthly_precipitation.pdf",
  landscape = TRUE,
  width.cm = 50, 
  height.cm = 21
)

# p1 <- precipitation_agg %>%  
#   dplyr::left_join(precipitation_decade_annual) %>% 
#   dplyr::mutate(Dekade_Label = sprintf("%s\n%3.1f mm/Jahr)",
#                                        .data$Dekade_Label,
#                                        round(.data$annual_mean, 1)))

p1 <- precipitation_agg

p2 <- precipitation %>% 
  dplyr::filter(.data$Jahr == max(.data$Jahr)) %>% 
  group_by_year_month() %>% 
  summarise_means()

n_decades <- length(unique(p1$Dekade_Label))

gg <- p1 %>% 
  ggplot2::ggplot(mapping = ggplot2::aes(
    x = as.integer(.data$Monat), 
    y = .data$mean,
    col = as.factor(.data$Dekade_Label)
  )) + 
  #ggplot2::geom_point(alpha = 0.5) + 
  ggplot2::geom_ribbon(ggplot2::aes_string(
    ymin = "q05", 
    ymax = "q95", 
    fill = "Dekade_Label"
  ), 
  alpha = 0.1
  ) + 
  kwb.impetus::scale_fill_decades(decades) +
  kwb.impetus::scale_color_decades(decades) +
  ggplot2::geom_point() +
  ggplot2::geom_point(ggplot2::aes(
    x = as.integer(.data$Monat),
    y = .data$mean
  ), 
  data = p2,
  col = "darkgrey",
  alpha = 0.5, 
  inherit.aes = FALSE,
  show.legend = FALSE
  ) +
  ggplot2::scale_x_continuous(
    breaks = 1:12, 
    labels = 1:12, 
    minor_breaks = NULL
  ) +
  #ggplot2::geom_boxplot() +
  ggplot2::facet_wrap( 
    ~ .data$Dekade_Label,
    nrow = 1L, 
    ncol = n_decades
  ) +
  ggplot2::theme_bw() + 
  ggplot2::theme(legend.position = "bottom") +
  ggplot2::labs(
    y = "Monatsmittel Niederschlag (mm/Monat)", 
    x = "Monatsnummer", 
    col = "Mittelwert", 
    fill = "5%/95% Konf.-intervall",
    title = unique(p1$Label)
  )

print(gg)

dev.off()
```

### Potential Evaporation

```{r potential_evaporation}
para_name <- "potential evaporation"

potential_evaporation <- kwb.impetus::dwd_berlin_monthly %>% 
  dplyr::filter(.data$parameter == para_name) %>%  
  dplyr::mutate(
    Jahr = as.integer(.data$year), 
    Dekade = kwb.impetus::floor_decade(.data$year),
    Dekade_Label = kwb.impetus::decade_label(.data$Dekade),
    Monat = as.factor(.data$month),
    Label = sprintf("DWD, monthly %s", .data$parameter)
  )

potential_evaporation_agg <- potential_evaporation %>% 
  group_by_decade_month_label %>% 
  summarise_means()

n_decades <- length(unique(potential_evaporation_agg$Dekade_Label))

decade_colors <- c('darkgreen', 'lightgreen', 'orange', 'red')

n_colors <- length(decade_colors)

decades <- tibble::tibble(
  names = unique(potential_evaporation_agg$Dekade_Label)[order(unique(potential_evaporation_agg$Dekade_Label))],
  values = decade_colors
)

potential_evaporation_decade_annual <- potential_evaporation_agg %>%  
  group_by_decade_label() %>% 
  dplyr::summarise(annual_mean = sum(.data$mean))

kwb.utils::preparePdf(
  "dwd_monthly_potential-evaporation.pdf",
  landscape = TRUE,
  width.cm = 35, 
  height.cm = 21
)

# p1 <- precipitation_agg %>%  
#   dplyr::left_join(precipitation_decade_annual) %>% 
#   dplyr::mutate(Dekade_Label = sprintf("%s\n%3.1f mm/Jahr)",
#                                        .data$Dekade_Label,
#                                        round(.data$annual_mean, 1)))

p1 <- potential_evaporation_agg

p2 <- potential_evaporation %>% 
  dplyr::filter(.data$Jahr == max(.data$Jahr)) %>% 
  group_by_year_month() %>% 
  summarise_means()

n_decades <- length(unique(p1$Dekade_Label))

gg <- p1 %>% 
  ggplot2::ggplot(mapping = ggplot2::aes(
    x = as.integer(.data$Monat), 
    y = .data$mean,
    col = as.factor(.data$Dekade_Label)
  )) + 
  #ggplot2::geom_point(alpha = 0.5) + 
  ggplot2::geom_ribbon(
    ggplot2::aes_string(
      ymin = "q05", 
      ymax = "q95", 
      fill = "Dekade_Label"
    ), 
    alpha = 0.1
  ) + 
  kwb.impetus::scale_fill_decades(decades) +
  kwb.impetus::scale_color_decades(decades) +
  ggplot2::geom_point() +
  ggplot2::geom_point(
    ggplot2::aes(x = as.integer(.data$Monat), y = .data$mean), 
    data = p2,
    col = "darkgrey",
    alpha = 0.5, 
    inherit.aes = FALSE,
    show.legend = FALSE
  ) +
  ggplot2::scale_x_continuous(breaks = 1:12, labels = 1:12, minor_breaks = NULL) +
  #ggplot2::geom_boxplot() +
  ggplot2::facet_wrap(
    ~ .data$Dekade_Label,
    nrow = 1L, 
    ncol = n_decades
  ) +
  ggplot2::theme_bw() + 
  ggplot2::theme(legend.position="bottom") +
  ggplot2::labs(
    y = "Monatsmittel potentielle Verdunstung (mm/Monat)", 
    x = "Monatsnummer", 
    col = "Mittelwert", 
    fill = "5%/95% Konf.-intervall",
    title = unique(p1$Label)
  )

print(gg)

dev.off()
```

## Download

The plots created with the code above were exported into `pdf` files, which are 
available for download here:

```{r download, echo = FALSE, results ='asis'}
files <- sprintf(
  "dwd_monthly_%s.pdf", c("potential-evaporation", "precipitation")
)

cat(paste0(
  sprintf("- [%s](https://kwb-r.github.io/kwb.impetus/%s)", files, files),
  collapse = "\n\n"
))
```
